import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import styles from "../styles/Home.module.css";
import { getproducts } from "../utilities/getProducts";
import { Product } from "../types/product";
import { CartProvider } from "../context/CartContext";
import Filter from "../components/Filter";
import { ItemsList } from "../components/Home";

interface IProps {
  products: Product[];
}
const Home = ({ products }: IProps) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Shopping.com</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <CartProvider>
          <Header />
          <Filter products={products} />
          {/* <ItemsList products={products} /> */}
        </CartProvider>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async (context) => {
  const products = await getproducts();
  return {
    props: {
      products,
    },
  };
};
